language: python
python:
  - 2.7
  - 3.6

before_script:
  - pip install pep8
script:
  - pep8 --max-line-length=99 style
  - python -m unittest discover
  - python setup.py sdist bdist_wheel --universal
